// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurneraJardin.Api.Data;

#nullable disable

namespace TurneraJardin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002222332_AddParentAndChildLastNames")]
    partial class AddParentAndChildLastNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TurneraJardin.Api.Models.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Disponibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int>("DuracionBloqueMinutos")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId", "DiaSemana", "HoraInicio")
                        .IsUnique();

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sala")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoNino")
                        .HasColumnType("longtext");

                    b.Property<string>("ApellidoPadre")
                        .HasColumnType("longtext");

                    b.Property<bool>("ConfirmacionEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<string>("EmailPadre")
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<string>("LinkMeet")
                        .HasColumnType("longtext");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreNino")
                        .HasColumnType("longtext");

                    b.Property<string>("NombrePadre")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<bool>("RecordatorioEnviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TelefonoPadre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DocenteId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordTemporalVenceUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("VersionSesion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Disponibilidad", b =>
                {
                    b.HasOne("TurneraJardin.Api.Models.Docente", "Docente")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Turno", b =>
                {
                    b.HasOne("TurneraJardin.Api.Models.Docente", "Docente")
                        .WithMany("Turnos")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Usuario", b =>
                {
                    b.HasOne("TurneraJardin.Api.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("TurneraJardin.Api.Models.Docente", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
